# Generated by Django 4.1.7 on 2023-02-23 21:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="book",
            name="author_name",
            field=models.CharField(default="author", max_length=100),
            preserve_default=False,
        ),
    ]
